use_frameworks!

target 'SwiftTickerView_Example' do
  pod 'SwiftTickerView', :path => '../'

  target 'SwiftTickerView_Tests' do
    inherit! :search_paths

    
  end
end

target 'appletv' do
    pod 'SwiftTickerView', :path => '../'
    
    target 'appletvTests' do
        inherit! :search_paths
        
        
    end
end
